main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/',views.profile,name='profile'),
    path('contactMe/',views.contactMe,name='contactMe'),
    path('index/',views.index,name='index'),
    path('matakuliah/',views.matakuliah,name='matakuliah'),
    path('delete/<int:item_id>/',views.hapus,name='delete'),
    path('deletekegiatan/<int:item_id>/',views.hapus_kegiatan,name='deletekegiatan'),
    path('deleteanggota/<int:item_id>/',views.hapus_kegiatan,name='delete_anggota'),
    path('kegiatan/',views.kegiatan,name='kegiatan'),
    path('buku/',views.buku),
    path('data/',views.data,name='data')
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime,date

# Create your models here.

class MataKuliah(models.Model):
    nama_matakuliah = models.CharField(max_length=30)
    dosen = models.CharField(max_length=30)
    sks = models.CharField(max_length=2)
    deskripsi = models.CharField(max_length=30)
    semester_tahun = models.CharField(max_length=30)
    ruang_kelas = models.CharField(max_length=10)

    # def __str__(self):
    #     return self.nama_matakuliah

class Post(models.Model):
    author = models.ForeignKey(MataKuliah, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    published_date = models.DateTimeField(default=timezone.now)

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=30)
    
    
class AnggotaKegiatan(models.Model):
    anggota_kegiatan = models.CharField(max_length=30)
    kegiatan = models.ForeignKey(Kegiatan,on_delete=models.CASCADE)

main/forms.py
from django import forms
from .models import MataKuliah,Kegiatan,AnggotaKegiatan

class MataKuliahForm(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields =['nama_matakuliah','dosen','sks','deskripsi','semester_tahun','ruang_kelas']

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = ['nama_kegiatan']

class AnggotaForm(forms.ModelForm):
    class Meta:
        model = AnggotaKegiatan
        fields = ['anggota_kegiatan']

main/views.py
from django.shortcuts import render,redirect
from django.core.mail import send_mail
from .models import MataKuliah,Post,Kegiatan,AnggotaKegiatan
from django.http import HttpResponseRedirect,JsonResponse
from .forms import MataKuliahForm,KegiatanForm,AnggotaForm
from django.contrib import messages
import requests
import json


def home(request):
    return render(request, 'main/portofolio.html')

def profile(request):
    return render(request, 'main/profile.html')

def contactMe(request):
    # if request == "POST":
    #     name = request.Post['name'] 
    #     email = request.Post['email']  
    #     subject = request.Post['subject']
    #     message = request.Post['message']        
    #     send_mail(name+subject,message,email,['muadzaskar19@gmail.com'])
    #     return redirect(request, 'main/ContactMe.html')
    # else:
        return render(request, 'main/ContactMe.html')

def index(request):
    return render(request, 'main/index.html')


# def saveform(request):
#     mata_kuliah = MataKuliah.objects.all()
#     response['mata_kuliah'] = mata_kuliah

#     return render(request,'main/kuliah.html',response)
# def form(request):
#     if request.method == 'POST':
#         form = MataKuliahForm()
#         if form.is_valid():
#             form.save()
#     form = MataKuliahForm()
#     return render(request,'main/kuliah.html',{'form':form})


def matakuliah(request):
    form = MataKuliahForm()
    if request.method == 'POST':
        form = MataKuliahForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/matakuliah')
    data = MataKuliah.objects.all()
    context = {'form':form,'data':data}
    return render(request,'main/kuliah.html',context)

def kegiatan(request):
    kegiatan_form = KegiatanForm()
    if request.method == 'POST':
        kegiatan_form = KegiatanForm(request.POST)
        if kegiatan_form.is_valid():
            kegiatan_form.save()
            return redirect('/kegiatan')
    anggota_form = AnggotaForm()
    if request.method == 'POST':
        anggota_form = AnggotaForm(request.POST)
        # if anggota_form.is_valid():
        #     anggota_form.save()
        #     return redirect('/kegiatan')
    # data_anggota = AnggotaKegiatan.objects.all()
    data_kegiatan = Kegiatan.objects.all()
    context_kegiatan = {'kegiatan_form':kegiatan_form,'data_kegiatan':data_kegiatan,'anggota_form':anggota_form}
    return render(request,'main/kegiatan.html',context_kegiatan)

# def anggota(request):
#     anggota_form = AnggotaForm()
#     if request.method == 'POST':
#         anggota_form = AnggotaForm(request.POST)
#         if anggota_form.is_valid():
#             anggota_form.save()
#             return redirect('/kegiatan')
#     data_anggota = AnggotaKegiatan.objects.all()
#     context = {'anggota_form':anggota_form,'data_anggota':data_anggota}
#     return render(request,'main/kegiatan.html',context)

def hapus_kegiatan(request,item_id):
    item = Kegiatan.objects.get(id=item_id)
    item.delete()   
    return redirect('/kegiatan')

# def hapus_anggota(request,item_id):
#     item = anggota.objects.get(id=item_id)
#     item.delete()   
#     return redirect('/kegiatan')

def hapus(request,item_id):
    item = MataKuliah.objects.get(id=item_id)
    item.delete()   
    return redirect('/matakuliah')

def tambah(request):
    data = MataKuliah.objects.all()
    return render(request,'main/kuliah.html',{'data':data})
    # mata_kuliah = MataKuliah.objects.all()
    # response['mata_kuliah'] = mata_kuliah

    # return render(request,'main/kuliah.html',response)
# def detail(request):

#     return render(request,'main/detail.html',{'data',data})

def buku(request):
    response = {}
    return render(request,'main/buku.html',response)

def data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret = requests.get(url)
    data = json.loads(ret.content)

    if not request.user.is_authenticated:
        i = 0
        for x in data['items']:
            del data['items'][i]['volumeInfo']['imageLinks']['smallThumbnail']
            i += 1
    return JsonResponse(data,safe=False)

main/templates/main/ContactMe.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %} 
    <title>Contact Me</title>
    {% endblock meta %}

    {% block content %}
    <header>
      <!-- Navbar -->
        <!-- Logo -->
        <a href='/' id="logo">PEWE</a>
        <!-- Logo -->
        <nav>
            <ul class="nav_links">
                <li><a id=a_nav href='/'>Portfolio</a></li>
                <li><a id=a_nav href='/profile'>About Me</a></li>
                <li id="this_page">Contact Me</li>
            </ul>
        </nav>
      <!-- Navbar -->
    </header>
    
    <h2 style="text-align: center; margin-bottom: 2rem;">Contact Me</h2>
    <!--Contact me form-->
    
      {% csrf_token %}
    <div class="row-form justify-content-center align-items-center">
      <!--Grid column-->
      <div class="col-md-9 mb-md-0 mb-5">
          <form id="contact-form" name="contact-form">
              <!--Grid row-->
              <div class="row-form">
                  <!--Grid column-->
                  <div class="col-md-6">
                      <div class="md-form mb-0">
                        <label>Your name</label>
                        <input type="text" name="name" class="form-control" class="text">
                      </div>
                  </div>
                  <!--Grid column-->
                  
                  <!--Grid column-->
                  <div class="col-md-6">
                      <div class="md-form mb-0">
                        <label>Your email</label>
                        <input type="email" name="email" class="form-control" class="text">
                      </div>
                  </div>
                  <!--Grid column-->

              </div>
              <!--Grid row-->

              <!--Grid row-->
              <div class="row-form">
                  <div class="col-md-12">
                      <div class="md-form mb-0">
                        <label>Subject</label>
                        <input type="text" name="subject" class="form-control" class="text">
                      </div>
                  </div>
              </div>
              <!--Grid row-->

              <!--Grid row-->
              <div class="row-form">
                  <!--Grid column-->
                  <div class="col-md-12">

                      <div class="md-form">
                        <label for="message">Your message</label>  
                        <textarea type="text" name="message" class="form-control md-textarea" class="text"></textarea> 
                      </div>

                  </div>
              </div>
              <!--Grid row-->
          
          <div class="text-center text-md-left">
              <a class="btn btn-primary" style="margin-left: 1rem;margin-top: 1rem;margin: 2rem 0 7rem 1rem;" type="submit">Send</a>
          </div>
        
          
      </div>
    </div>
  
    <!--Contact me form-->
    {% endblock content %}

main/templates/main/add.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %} 
    <title>Contact Me</title>
    {% endblock meta %}

    {% block content %}
    <header>
      <!-- Navbar -->
        <!-- Logo -->
        <a href='/' id="logo">PEWE</a>
        <!-- Logo -->
        <nav>
            <ul class="nav_links">
                <li><a id=a_nav href='/'>Portfolio</a></li>
                <li><a id=a_nav href='/profile'>About Me</a></li>
                <li><a id=a_nav href='/contactMe'>Contact Me</a></li>
            </ul>
        </nav>
      <!-- Navbar -->
    </header>
    <h2 style="text-align: center; margin-bottom: 2rem;">Mata Kuliah</h2>
    
    
    
                
            
            
            <h2 style="text-align: center; margin-bottom: 2rem;"> Mata Kuliah anda</h2>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Mata Kuliah</th>
                    <th scope="col">Dosen Pengajar</th>
                    <th scope="col">sks</th>
                    <th scope="col">Ruang Kelas</th>
                    <th scope="col">Semester tahun</th>
                    <th scope="col">Deskripsi</th>
                  </tr>
                </thead>
                <tbody>
                    {% for x in data%}
                  <tr>
                        <td>{{ x.nama_matakuliah}}</td>
                        <td>{{ x.dosen}}</td>
                        <td>{{ x.sks}}</td>
                        <td>{{ x.semester_tahun}}</td>
                        <td>{{ x.ruang_kelas}}</td>
                        <td>{{ x.deskripsi }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        
        
      
  
    <!--Mata Kuliah form-->
    {% endblock content %}

main/templates/main/buku.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Cari Buku</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

{% endblock meta %}

{% block content %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">Story</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
            <a class="nav-link" href="buku.html">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input  class="form-control mr-sm-2" id="cari" placeholder="Cari Rekomendasi Buku" aria-label="Search">
        </form>
        {% if user.is_authenticated %}
        <a class="btn btn-primary" href="/admin/logout/?next=/buku" role="button"><span class='glyphicon glyphicon-log-in'></span>Logout</a>
        {% else %}
        <a class="btn btn-primary" href="/admin/login/?next=/buku" role="button"><span class='glyphicon glyphicon-log-in'></span>Login</a>
        {% endif %}
        </div>
    </nav>
    {% if not request.user.is_authenticated %}
    <h2 style="text-align: center;">Halo, Berikut Rekomendasi Buku</h2>
    <h6 style="text-align: center;">Lakukan Search untuk Kategori yang anda inginkan</h6>
    <p style="text-align: center;">Untuk mendapatkan gambar lakukan login terlebih dahulu</p>
    {% else %}
    <h2 style="text-align: center;">Halo {{user.get_username}}, Berikut Rekomendasi Buku</h2>
    <h6 style="text-align: center;">Lakukan Search untuk Kategori yang anda inginkan</h6>
    
    {% endif %}
    <table style="width:100%" id="daftar_buku">
    </table>
    
    <script type="text/javascript">
        $("#cari").keyup(function(){
            var input = $("#cari").val();
            console.log(input);
            $.ajax({
                url: '/data?q=' + input,
                success: function(data){
                    var array_items = data.items;
                    
                    $("#daftar_buku").empty();
                    for(i=0;i<array_items.length;i++){
                        judul_buku = array_items[i].volumeInfo.title;
                        gambar = array_items[i].volumeInfo.imageLinks.smallThumbnail;
                        console.log(array_items);
                        $("#daftar_buku").append(
                            "<tr><th>"+judul_buku+"</th><th><img src="+gambar+"></th></tr>"
                            )
                    }
                }

            })
        });
    </script>
{% endblock content %}

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %} 
    <title>Contact Me</title>
    {% endblock meta %}

    {% block content %}
    <header>
      <!-- Navbar -->
        <!-- Logo -->
        <a href='/' id="logo">PEWE</a>
        <!-- Logo -->
        <nav>
            <ul class="nav_links">
                <li><a id=a_nav href='/'>Portfolio</a></li>
                <li><a id=a_nav href='/profile'>About Me</a></li>
                <li><a id=a_nav href='/contactMe'>Contact Me</a></li>
            </ul>
        </nav>
      <!-- Navbar -->
    </header>
    <h2 style="text-align: center; margin-bottom: 2rem;">Mata Kuliah</h2>
    <form action="" method="Post">
        {% csrf_token %}
        {{ form }}
        <!-- {% for field in form %}
        <p>{{ field }}</p>
        {% endfor %} -->
        <input type="submit" value="Submit">
    </form>
    
    
                
            
            
            <h2 style="text-align: center; margin-bottom: 2rem;"> Mata Kuliah anda</h2>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Mata Kuliah</th>
                    <th scope="col">Dosen Pengajar</th>
                    <th scope="col">sks</th>
                    <th scope="col">Ruang Kelas</th>
                    <th scope="col">Semester tahun</th>
                    <th scope="col">Deskripsi</th>
                  </tr>
                </thead>
                <tbody>
                    {% for x in data%}
                  <tr>
                        <td>{{ x.nama_matakuliah}}</td>
                        <td>{{ x.dosen}}</td>
                        <td>{{ x.sks}}</td>
                        <td>{{ x.semester_tahun}}</td>
                        <td>{{ x.ruang_kelas}}</td>
                        <td>{{ x.deskripsi }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        
        
      
  
    <!--Mata Kuliah form-->
    {% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}

    {% block meta %}
    <title>Muadz</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
      
    </script>
    {% endblock meta %}
    
    {% block content %}
  
    
    <div class="row justify-content-center align-items-center"  id="home">
        <div class="col-4" style="color: #222098;" >
            <img src="{% static 'img/foto.jpg' %}" alt="foto saya" class="foto" width="300" height="400" >
            
           
        </div>
        <div class="col-4">
            <h1>Hai,Nama saya Muadz</h1>
            <article>NPM   : 1906398774</article>
            <article>Hobi  : Olahraga</article>
            <h3>Tentang saya</h3>
            <P>Saya adalah mahasiswa fasilkom angkatan 2019(maung). Jurusan saya adalah ilmu komputer.</P>
            <p>Kesibukan saya selama kuliah cuma belajar,sedikit organisasi sama nonton film</p>
            <a href="https://www.linkedin.com/" class="btn btn-primary" style="margin-top:2rem;display: block; width: 10rem;">Hubungi saya</a>
        </div>
      </div>
      
      <div class="row justify-content-center align-items-center" >
        <div class="col-8" style="color: #222098;" >
            <h2>Riwayat Pendidikan</h2>
                <ul>
                    <li>SMAN 8 Jakarta</li>
                    <li>SMPI Al-azhar 12 Rawamagun</li>
                    <li>SDI Al-azhar 13 Rawamangun</li>
                </ul>
                <a href='/matakuliah'>Aktivitas Kuliah</a>   
           
        </div>
    </div>
    <div class="row justify-content-center align-items-center" >
      <div id="accordion" class="col-8">
        <div class="group1">
        <h3 class="accordion">Aktivitas saat ini<button style="float:right" id="t12">turun</button><button style="float:right" id="n13">naik</button></h3>
        <div class="panel">
          <p>
          Kuliah - nugas - kuliah nugas
          </p>
        </div>
        </div>
        <div class="group2">
        <h3 class="accordion">Pengalaman organisasi/kepanitiaan<button style="float:right" id="t23">turun</button><button style="float:right" id="n21">naik</button></h3>
        <div class="panel">
          <p>
          Organisasi BEM,SISTEM,RISTEK
          </p>
        </div>
        </div>
        <div class="group3">
        <h3 class="accordion">Prestasi<button style="float:right" id="t31">turun</button><button style="float:right" id="n32">naik</button></h3>
        <div class="panel">
          <p>
          Untuk dapat mendapatkan prestasi diperlukan pejuangan besar. Prestasi saya adalah juara lomba a,lomba b,lomba c 
          </p>
        </div>
        </div>
      </div>
    </div>
    
    <style>
    body{
        background-color: #FB9E2E;;
    }
    .foto{
        vertical-align:middle;
    }
    .coloumn{
        float : left;
        width : 48px;
    }

    .row::after{
        content: "";
        clear: both;
        display: table;
    }
    article{
        color:blue;
    }
    .accordion {
      background-color: #eee;
      color: #444;
      cursor: pointer;
      padding: 18px;
      width: 100%;
      border: none;
      text-align: left;
      outline: none;
      font-size: 15px;
      transition: 0.4s;
    }

    .active, .accordion:hover {
      background-color: #ccc; 
    }
    button {
      background-color: blue; 
    }

    .panel {
      padding: 2px 25px;
      display: none;
      background-color: wheat;
      overflow: hidden;
      margin-bottom: 5px;
    }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
          $( "#accordion" )
          var acc = document.getElementsByClassName("accordion");
          var i;

          for (i = 0; i < acc.length; i++) {
            acc[i].addEventListener("click", function() {
              this.classList.toggle("active");
              var panel = this.nextElementSibling;
              if (panel.style.display === "block") {
                panel.style.display = "none";
              } else {
                panel.style.display = "block";
              }
           
          });
          }
        
        
          $("#t12").click(function(){
              var x =$(".group1").next()
              $(".group1").before(x)
          });
          $("#t23").click(function(){
              var x =$(".group2").next()
              $(".group2").before(x)
          });
          $("#t31").click(function(){
              var x =$(".group3").next()
              $(".group3").before(x)
          });
          $("#n21").click(function(){
              var x =$(".group2").prev()
              $(".group2").after(x)
          });
          $("#n32").click(function(){
              var x =$(".group3").prev()
              $(".group3").after(x)
          });
          $("#n13").click(function(){
              var x =$(".group1").prev()
              $(".group1").after(x)
          });

    </script>
    {% endblock content %}

main/templates/main/kegiatan.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %} 
    <title>Kegiatan</title>
    {% endblock meta %}

    {% block content %}
    <header>
      <!-- Navbar -->
        <!-- Logo -->
        <a href='/' id="logo">PEWE</a>
        <!-- Logo -->
        <nav>
            <ul class="nav_links">
                <li><a id=a_nav href='/'>Portfolio</a></li>
                <li><a id=a_nav href='/matakuliah'>Kuliah</a></li>
                <li><a id=a_nav href='/kegiatan'>Kegiatan</a></li>
            </ul>
        </nav>
      <!-- Navbar -->
    </header>
    <form action="" method="Post">
        {% csrf_token %}
        {{ kegiatan_form }}
        <input type="submit" value="Tambah Kegiatan">
    </form>
        <div class="row-3">
        <div class="col-sm-2">
            <div class="card">
                {% for x in data_kegiatan %}
            <div class="card-body">
                <h5 class="card-title">{{ x.nama_kegiatan }}</h5>
                <a type="submit" href={%url 'main:deletekegiatan' x.id%}>Hapus kegiatan</a>
                <ul>
                {% for y in data_anggota%}
                    <li>{{ y.anggota_kegiatan }}</li>
                {% endfor %}
                </ul>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ anggota_form }}
                    <input type="submit" value="Tambah Anggota">
                </form>
            </div>
                {% endfor %}
            </div>
        </div>
        </div>
    {% endblock content %}

main/templates/main/kuliah.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %} 
    <title>Mata Kuliah</title>
    {% endblock meta %}

    {% block content %}
    <header>
      <!-- Navbar -->
        <!-- Logo -->
        <a href='/' id="logo">PEWE</a>
        <!-- Logo -->
        <nav>
            <ul class="nav_links">
                <li><a id=a_nav href='/'>Portfolio</a></li>
                <li><a id=a_nav href='/profile'>About Me</a></li>
                <li><a id=a_nav href='/contactMe'>Contact Me</a></li>
            </ul>
        </nav>
      <!-- Navbar -->
    </header>
    <h2 style="text-align: center; margin-bottom: 2rem;">Mata Kuliah</h2>
    <form action="" method="Post">
        {% csrf_token %}
        {{ form }}
        <!-- {% for field in form %}
        <p>{{ field }}</p>
        {% endfor %} -->
        <input type="submit" value="Submit">
    </form>
    
    
                
            
            
            <h2 style="text-align: center; margin-bottom: 2rem;"> Mata Kuliah anda</h2>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Mata Kuliah</th>
                    <th scope="col">Dosen Pengajar</th>
                    <th scope="col">sks</th>
                    <th scope="col">Ruang Kelas</th>
                    <th scope="col">Semester tahun</th>
                    <th scope="col">Deskripsi</th>
                  </tr>
                </thead>
                <tbody>
                    {% for x in data%}
                  <tr>
                        <td>{{ x.nama_matakuliah}}</td>
                        <td>{{ x.dosen}}</td>
                        <td>{{ x.sks}}</td>
                        <td>{{ x.semester_tahun}}</td>
                        <td>{{ x.ruang_kelas}}</td>
                        <td>{{ x.deskripsi }}</td>
                        <td><a type="submit" href={%url 'main:delete' x.id%}>Delete</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        
        
      
  
    <!--Mata Kuliah form-->
    {% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">Story</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
        <a class="nav-link" href="buku.html">Home <span class="sr-only">(current)</span></a>
        </li>
    </ul>
</nav>
<h2>Log In</h2>
<h4>{% trans 'Log in' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Log in' %}</button>

    </form>
</form>
{% endblock content %}

main/templates/main/profile.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %}
    <title>Profile</title>
    {% endblock meta %}


  {% block content %}
    <header>
       
        <a href='/' id="logo">PEWE</a>
        <nav>
            <ul class="nav_links">
                <li><a id=a_nav href='/'>Portfolio</a></li>
                <li id="this_page">About Me</a></li>
                <li><a id=a_nav href='/contactMe'>Contact Me</a></li>
            </ul>
        </nav>
        
        
    </header>
    <div class=profile-wrap" id="page23">
        <div class="row justify-content-center align-items-center" style="height: 540px;">
            <div class="col-3"  >
              <article style="color: #222098"><b>HELLO</b></article>
                <h2>I Am PEWE</h2>
                <article style="color: #222098"><b>WEB PROGRAMMING</b></article>
                <article style="color: #222098">I'm active web programming,energic,</article>
                <article style="color: #222098">cheerful and of course an expert in coding</article>
                <article style="margin-top: 2rem;color: #222098">campus ID  1702323424</article>
                <article style="color: #222098">Start Year: 2017</article>
                <article style="color: #222098">Faculty of computer science</article>
                <article style="color: #222098">Universitas Indonesia</article>
            </div>
            <div class="col-3">
                <img src="{% static 'img/pewe2.jpg' %}" class="rounded" alt="Kak Pewe" style="height: 300px;width: 350px" srcset="">
            </div>
        </div>
    </div>
  {% endblock content %}